FROM ghcr.io/nakarma/containers/rpios-builder:armhf-latest

ENV DEBIAN_FRONTEND noninteractive

RUN apt update \
    && apt -y full-upgrade \
    && apt -y install libsdl*dev \
    && apt -y build-dep mesa \
    && apt-get -y --purge autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["bash"]
